import { createContext } from "react";

export const AppContext = createContext({
  email: "",
  otp: "",
  names: {},
  namesLong: {},
  namesDynamicShort: {},
  namesDynamicLong: {},
  buyingPowerStatic: [],
  buyingPowerStaticLong: [],
  buyingPowerDynamicShort: [],
  buyingPowerDynamicLong: [],
  tableVisibility: [],
  staticLevelDefaultValue: [],
  recordLimit: null,
  profilePhoto: null,
  userData: {
    first_name: "",
    last_name: "",
    slackID: "",
    phone: "",
    email: "",
  },
  theme: "",
  signupData: {
    first_name: "",
    email1: "",
    email2: "",
    password: "",
  },
  isAdmin: false,
  superUser: false,
  subscriptionHistory: [],
  subscription: null,
  dashboardKey: null,
  staticShortKey: null,
  staticLongKey: null,
  dynamicShortKey: null,
  dynamicLongKey: null,
  dynamicNextGameShortKey: null,
  dynamicNextGameLongKey: null,
  subscriptionFeatures: {},
  adminDashboard: {},
  supportUserData: [],
  couponList: [],
  couponList2: [],
  userList: [],
  comparisonFeatures: [{ name: "", basic: false, plus: false, premium: false }],
  feature: [],
  apiKeys: [],
  plans: [],
  adminDashboardData: null,
  nextGamePlanShort: false,
  nextGamePlanLong: false,
  selectedUser: null,
  shortMatrixLength: 6,
  longMatrixLength: 12,
  setAppContext: () => { },
});
