import React from 'react';
import { Link } from 'react-router-dom';
import BackIcon from '../assets/svg/BackIcon.svg';

const TermsofService = () => {
  return (
    <div className='max-w-7xl mx-auto p-4'>
      <div className='mt-3 lg:mt-5 p-4 lg:p-[30px] rounded-md bg-background6 shadow-[0px_0px_6px_0px_#28236633]'>
        <div className='flex items-center gap-3 lg:gap-5'>
          <Link to="/"><img className='w-3 h-5 lg:w-auto' src={BackIcon} alt="" /></Link>
          <h3 className='text-lg lg:text-[28px] lg:leading-[42px] font-semibold text-Primary'>Terms of Service</h3>
        </div>
        <p className='mt-3 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>1. General Information </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>The Option Matrix app provides tools and data-driven insights designed to assist users in making informed decisions regarding SPX option trade ideas generated by the InsideOption program. By using the app, you agree to comply with these terms and conditions and acknowledge that the app is intended as a supplemental tool for evaluating trade strategies, not as a definitive source of financial advice. </p>

        <p className='mt-3 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>2. Not Financial Advice </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>The information provided by the Option Matrix app, including trade recommendations, suggested contract levels, or matrix details, is for educational and informational purposes only. </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>We are not financial advisors, and the app should not be considered financial or investment advice. </p>

        <p className='mt-3 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>3. User Responsibility </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>By using the app, you acknowledge that: </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>Trading options carries a high level of risk, and financial losses can occur. </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>All trades and investment decisions you make based on the app's recommendations are your sole responsibility. </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>We do not guarantee profits or the accuracy of the information provided within the app. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>4. Pricing </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>The fees for our software services are outlined in the pricing plan selected by you. We reserve the right to change our pricing at any time with notice. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>5. Payment </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>You agree to pay all fees in accordance with the payment terms specified in the selected pricing plan. Failure to pay fees may result in the suspension or termination of your access to the software services. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>6. Refund Policy </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>Once purchased and subscription plan, we do not provide any kind of refund or replacement of the subscription plan, However we are open to discuss any issues if arise.</p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>7. Non-Refundable Access </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>If you choose to discontinue your membership or are removed from the Inside Option group by the group owner (David Chau), no refunds will be issued, and your access to OptionMatrixApp will be revoked. Continued access to OptionMatrixApp is exclusively for active members of the Inside Option program. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>8. Prohibited Sharing </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>Sharing any content from the Option Matrix app with non-subscribers is strictly prohibited. If any such activity is identified, your access will be permanently revoked, including access to future enhancements or related tools.</p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>9. Limitation of Liability </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>The creators and operators of the Option Matrix app will not be held liable for any financial losses, damages, or costs incurred as a result of using the app. </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>The app does not take into account individual financial circumstances, goals, or risk tolerance. </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>You use the app and its insights at your own risk. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>10. No Guarantees </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>The app is designed to provide an analytical framework, but it does not guarantee that suggested trades or strategies will result in financial gains. Past performance is not indicative of future results. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>11. Educational Purpose </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>Our goal is to provide a tool to help users understand and strategize their trades. The app is intended to complement, not replace, independent financial decision-making. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>12. Use of the App </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>By using the app, you agree to: </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>Follow all applicable laws and regulations related to trading. </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>Use the app responsibly and acknowledge that the app is one of many tools available for trade analysis. </p>

        <p className='mt-2 lg:mt-5 text-sm lg:text-lg text-Primary font-medium'>13. Updates to the Terms of Service </p>
        <p className='mt-1 text-sm lg:text-lg text-Secondary2'>We reserve the right to update these terms at any time. Continued use of the app indicates your acceptance of any modifications to these terms. </p>

        <Link to="/"> <p className='mt-5 text-sm lg:text-lg text-Secondary2 text-center'>Back To Home</p></Link>
      </div>
    </div>
  );
}

export default TermsofService;
